### ISSUE TITLE
When libs.versions.toml already exists, comments are removed

### ISSUE THREAD

**Issue by plnice** [littlerobots/version-catalog-update-plugin#1]
When plugin is applied on a project that already contains `libs.versions.toml` with some commented lines, after running `./gradlew versionCatalogUpdate` they are removed. I use comments to visually split long list of versions/libraries into logical groups. See attached diff:

![image](https://user-images.githubusercontent.com/1078123/139916513-e2c03577-01a0-4ebf-9ea7-e08c59c8db86.png)

(running with `sortByKey false`, `keepUnused true`)

**Comment by hvisser** [comment]
That's a great point. The comments are lost during parsing, but it would indeed be good if it would be possible to retain them somehow.

**Comment by plnice** [comment]
I think that the simplest solution here is to add a new configuration flag (e.g. `keepComments`) and make it work only when `sortByKey` is set to `false` and `keepUnused` is set to `true`. With such a setup, we could extend `VersionCatalog` model class with the map of the line number to the comment content. Then, when writing new file content, we could track current line number and print the comment when the map contains an entry with that line number. Would you accept a PR with such a solution?

In the future, as a second step, we could remove `keepUnused true` requirement by only marking unused versions/libraries/bundles/plugins in the `VersionCatalog` model with some flag and ignoring entries marked as unused in the `VersionCatalogWriter`. But I think that would add some logic on the writer level, and should be avoided.

Other solutions would require having some strong assumptions about the comments, like "comment always denotes section start". Then `VersionCatalog` structure should be changed in such way:
- each of the versions/libraries/bundles/plugins group can have named subgroups,
- the first subgroup can be unnamed,
- there can be empty subgroups (two commented lines in a row). 

`sortByKey` would then have to operate within that each of the subgroup (subgroup content would be sorted, not all versions/libraries/bundles/plugins). But that would be an overkill solution, I guess.

**Comment by hvisser** [comment]
Well the main issue is also that the parser used for the TOML parsing is not processing any comments so that would then mean that the comments needs to be bolted on after the fact, which already a bit problematic IMHO...And like you mention there's a lot of things that _don't_ work when you want to keep comments, so I'm unsure if this is really feasible in a practical way. 

It might be more practical to re-add the comments from VCS again if you feel that they are really important for now or use a prefix in your library keys as a form of grouping them.

**Comment by plnice** [comment]
Oh, I missed the fact that the Jackson is used to parse TOML...

In my projects I will still be using comments since prefixes (which I have anyway) are not that readable in TOML file with many entries, but will go with re-adding the comments from VCS.
