### ISSUE TITLE
`build/dependencyUpdates/report.json` missing; passing `-DoutputFormatter=json` explicitly needed

### ISSUE THREAD

**Issue by PawelLipski** [littlerobots/version-catalog-update-plugin#100]
See this [CI pipeline](https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/8500/workflows/9054b8fa-5ab5-4f6e-a330-53ab9c0dd43f/jobs/8931):

```
Generated report file build/dependencyUpdates/report.txt

> Task :versionCatalogUpdate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':versionCatalogUpdate' (type 'VersionCatalogUpdateTask').
  - In plugin 'nl.littlerobots.version-catalog-update' type 'nl.littlerobots.vcu.plugin.VersionCatalogUpdateTask' property 'reportJson' specifies file '/root/git-machete-intellij-plugin/build/dependencyUpdates/report.json' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
```

The only report file that gets generated by [gradle-versions-filter plugin](https://github.com/janderssonse/gradle-versions-filter-plugin) is `build/dependencyUpdates/report.txt`; `report.json` expected by VCU plugin is missing.

Note that it might be the problem with gradle-versions-filter plugin rather than with VCU plugin; CCing @janderssonse just in case.

**Comment by PawelLipski** [comment]
Versions: 

```toml
[plugins]
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:0.7.0"
versionsFilter = "se.ascp.gradle.gradle-versions-filter:0.1.16"
```

Fix PR: https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1534

**Comment by janderssonse** [comment]
Thanks, I plan to do an overhaul of the plugin in a the not to distant future, and will have a look at this issue at the same time.

**Comment by hvisser** [comment]
One fix on the side of this plugin could be to use a separate dependencyUpdates task (not the default one), but then the issue is that you can no longer get away with configuring the versions task only once, so I'm not sure what the best solution would be.

**Comment by hvisser** [comment]
Circling back to this, VCU is already configuring the versions plugin to format all reports (https://github.com/littlerobots/version-catalog-update-plugin/blob/main/plugin/src/main/kotlin/nl/littlerobots/vcu/plugin/VersionCatalogUpdatePlugin.kt#L62) but it can be reconfigured. So I don't think I can do much about it here other than document that that report should be enabled.
