### ISSUE TITLE
Problem syncing project on Android Studion configured with gradle 8.0.2 and Java 11

### ISSUE THREAD

**Issue by markchristopherng** [littlerobots/version-catalog-update-plugin#107]
**Describe the issue**
When using gradle 8.0.2 and Java 11 with Android project using Android Studio Electric Eel | 2022.1.1

I am able to sync the project.

class org.gradle.initialization.DefaultSettings_Decorated cannot be cast to class org.gradle.api.Project (org.gradle.initialization.DefaultSettings_Decorated and org.gradle.api.Project are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @91161c7)
class org.gradle.initialization.DefaultSettings_Decorated cannot be cast to class org.gradle.api.Project (org.gradle.initialization.DefaultSettings_Decorated and org.gradle.api.Project are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @91161c7)

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Steps to reproduce**
Just trying to sync the project in Android Studio

**Stacktrace**
Please run Gradle with the `--stacktrace` option and share the output in case of a Gradle error.

**Comment by hvisser** [comment]
This is probably not related to this plugin, at least not as far as I can tell from the info provided. Keep in mind that AGP 8.x requires Java 17 so running it with Java 11 is not supported, which is most likely your issue.
