### ISSUE TITLE
dont decrease the version of library having latest version

### ISSUE THREAD

**Issue by umeshbagade** [littlerobots/version-catalog-update-plugin#116]
I know we can keep the versions using pin and keep, but I don't want to decrease the versions of my libraries. Is there any way I can keep latest versions if you can't update them?

Example:-
The following dependencies exceed the version found at the milestone revision level:
 - some.lib.ref [31.1 <- 23.0]

**Comment by hvisser** [comment]
Without additional context this seems to work as intended.

**Comment by umeshbagade** [comment]
> In this case you have declared a version that doesn't exist (according to the versions plugin) so the plugin is correcting it to the actual version used in your project. So basically your version definition was never used here.
> 
> Are you sure the version you have declared exists?

Yes that version exists,
Its the guava library with 31.1.jre version

**Comment by hvisser** [comment]
I suspect this is an issue with the dependency versions plugin (dependencies are not handled by this plugin). You can check the report.json to see what it believes to be the latest version. You can also try to run with `--refresh-dependencies` to force updating the cache.

If you have a small project that reproduces this I can take a look to verify.

**Comment by hvisser** [comment]
Adding `com.google.guava:guava:31.1-jre` to the version catalog and then running `./gradlew versionCatalogUpdate` yields the correct results for me.

Please also check that you didn't disable the dependency versions plugin `report.json` by mistake. This can lead to stale results. If unsure delete `build/dependencyUpdates/report.json` and run the plugin again. It should recreate that file.

**Comment by hvisser** [comment]
Have you tried running with `--refresh-dependencies` as noted in my comment here https://github.com/littlerobots/version-catalog-update-plugin/issues/116#issuecomment-1642788868 ? Since the dependencies are reported as exceeded this means that they weren't found as valid versions by the dependency versions plugin. Why that is is hard to tell. 

I'm not sure if ignoring exceeded would be the right call since the consequence of that might be that you think you are using some not existing version while you are actually on some other version.

**Comment by emartynov** [comment]
Yeah, I run and have the same effect. I have the next code in gradle:
```
apply plugin: 'com.github.ben-manes.versions'
apply plugin: 'nl.littlerobots.version-catalog-update'

/**
 * @return true if version is like `1.0-beta2`, `2.0-rc2`, `3.4-alpha05`
 *         false if version is like `3.0`, `4.4-final`, `release-0.6`, `v5.6.0`, `7.0 GA`
 *
 * Source https://github.com/ben-manes/gradle-versions-plugin
 */
def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

/**
 * Instruct task to exclude non stable versions unless the original one is also unstable
 * This will allow to see updates for alphas and betas, but will not show updates for used stable versions
 *
 * Source https://github.com/ben-manes/gradle-versions-plugin
 */
tasks.named('dependencyUpdates').configure {
    rejectVersionIf {
        isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)
    }
}

versionCatalogUpdate {
    // sort the catalog by key (default is true)
    sortByKey = false
}
```

Let me go ahead and remove the dependency update configuration and see if it probably changes things.

**Comment by emartynov** [comment]
Oke, as soon as I removed the dependency update configuration, I got previous changes and alpha/beta versions for many other AndroidX dependencies also.

**Comment by emartynov** [comment]
Thanks, I will create a ticket on the dependency update plugin repo.
