### ISSUE TITLE
Ignore beta versions 

### ISSUE THREAD

**Issue by wickenico** [littlerobots/version-catalog-update-plugin#117]
In my Kotlin Ktor project with Gradle I have often the problem that version catalogue update uses some weird beta versions for example from Kotlin, Ktor and other stuff. I want to use only the latest stable version of my plugins and libs.

**Comment by hvisser** [comment]
As mentioned in the readme, you should configure the versions plugin for that. See https://github.com/ben-manes/gradle-versions-plugin#rejectversionsif-and-componentselection

**Comment by wickenico** [comment]
Thanks!
