### ISSUE TITLE
Fail to resolve dependencies with gradle 8.6

### ISSUE THREAD

**Issue by antwanTR** [littlerobots/version-catalog-update-plugin#144]
**Describe the issue**
I started getting the issue after updating gradle to 8.6 
Lib version : 0.8.4

if I'm not mistaken this issue was fixed before for gradle 8.4 but it started to happen again after updating to 8.6 

**Stacktrace**

> * What went wrong:
Execution failed for task ':versionCatalogUpdate'.
> A plugin or custom build logic has included an old XML parser, which is not suitable for dependency resolution with this version of Gradle.
  You can work around this issue by specifying the SAXParserFactory to use or by updating any plugin that depends on an old XML parser version.

**Comment by hvisser** [comment]
This error is expected and it is thrown to let you know how to resolve it. Both this plugin and the dependency versions plugin throw this error, the link in the error has more details and a workaround. See #139 for the original issue.
