### ISSUE TITLE
Update from direct dependencies to catalogs

### ISSUE THREAD

**Issue by NikBomb** [littlerobots/version-catalog-update-plugin#145]
From the readme:

``` After you have created the libs.versions.toml file you can update your dependency references to use the catalog instead of direct dependency declarations. ```

Is there any plugin, feature to help with the above update process?

**Comment by hvisser** [comment]
Not that I'm aware of. Newer versions of IntelliJ have some support for this in the IDE.

**Comment by mavek87** [comment]
@hvisser I'm using the last version of intellij ultimate but cant find this thing anywhere. Do you have any hint?
