### ISSUE TITLE
Do not upgrade to RC (release candidate) versions

### ISSUE THREAD

**Issue by SchlauFuchs** [littlerobots/version-catalog-update-plugin#156]
when running the versionCatalogUpdate feature, I want this plugin to not upgrade to release candidate versions. There should be a way to configure this, as the versioning conventions are not absolutely stable.

**Comment by hvisser** [comment]
It's unclear what you have tried already. If you are using the dependency versions plugin then the README has links to the documentation on how to do that. 

For the new resolver, there's a similar mechanism, the `versionSelector` which you can leverage to filter by version and/or group/module etc. I think that should cover what you are asking.

**Comment by hvisser** [comment]
Closing for now as configuration of the versions plugin as documented will solve the issue. Feel free to reopen if that's not the case.
