### ISSUE TITLE
Unable to update plugin without version

### ISSUE THREAD

**Issue by Strawely** [littlerobots/version-catalog-update-plugin#22]
When I try to update plugin in [plugins] block I got error `Could not parse version or version.ref for plugin parcelize`
I think it will be better to return `VersionDefinition.Unspecified`.
If you're ok with that I can make a PR

**Comment by hvisser** [comment]
Can you give me an example of the entry in the catalog causing that issue? Are you not specifying any versions here?

**Comment by Strawely** [comment]
`detekt = { id = "io.gitlab.arturbosch.detekt" }`
