### ISSUE TITLE
autogenerated version catalog library names should not use "-"

### ISSUE THREAD

**Issue by kenyee** [littlerobots/version-catalog-update-plugin#30]
When you use .\gradlew versionCatalogUpdate --create
it generates a version catalog that looks like this:
```
...
[libraries]
androidx-annotation = "androidx.annotation:annotation:1.3.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
...
```

and then if you try using this like
```
implementation libs.androidx-annotation
```
Groovy thinks you're trying to do subtraction 😹 

Please make it generate the labels with underscores.... looks like a useful feature to autogen a version catalog....

**Comment by hvisser** [comment]
The syntax you are using is incorrect, if a key is using a dash they you should replace it with a dot, this is how Gradle replaces it. So the above declaration would be
`implementation libs.androidx.annotation`

**Comment by hvisser** [comment]
More on this in the Gradle docs here https://docs.gradle.org/7.3.3/userguide/platforms.html#sub:mapping-aliases-to-accessors

I hope that answers the question @kenyee? TL;DR unless I misunderstood your question I think there's no need to update the alias generation logic here.

**Comment by kenyee** [comment]
yes...it just is confusing that they automagically map "-" to "." :-)

**Comment by hvisser** [comment]
Yeah I can see that, though that's out of my control ;)
