### ISSUE TITLE
Publish to Gradle plugin portal

### ISSUE THREAD

**Issue by yschimke** [littlerobots/version-catalog-update-plugin#31]
See https://plugins.gradle.org/docs/publish-plugin

Expected a search to find it, but it didn't

**Comment by hvisser** [comment]
It's not so much registering there, it's actually a different repository. For now I prefer to publish to one repository only to not make things more complicated. So for now I'll stick to Maven Central unless there's a compelling reason to switch.

**Comment by hvisser** [comment]
OK reconsidering this, the plugin portal _is_ the default and it provides some better discovery too maybe.
