### ISSUE TITLE
Wrong Jackson version getting picked up?

### ISSUE THREAD

**Issue by michaelcarrano** [littlerobots/version-catalog-update-plugin#39]
I had this working previously and now running into this issue locally and on CI (our own hosted Github runners). It looks like this project defines a newer version of Jackson (2.13.0) but our project is not loading that version. It looks like we are picking up Jackson 2.11.1

Android Studio Chipmunk (stable)
AGP 7.2.0
Gradle 7.4.2

```
Generated report file build/dependencyUpdates/report.json
Generated report file build/dependencyUpdates/report.xml
Generated report file build/dependencyUpdates/report.txt

> Task :versionCatalogUpdate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':versionCatalogUpdate'.
> com.fasterxml.jackson.dataformat.toml.TomlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;
```

When I run with --stacktrace is points to https://github.com/littlerobots/version-catalog-update-plugin/blob/main/catalog/src/main/kotlin/nl/littlerobots/vcu/VersionCatalogParser.kt

Let me know what other information is needed.

**Comment by hvisser** [comment]
It sounds like indeed some plugin is pulling in an older version of Jackson and I'm guessing that that dependency "wins" somehow? Maybe a build scan shows where that dependency comes from? The toml is parsed using Jackson and it requires that version or newer.

**Comment by hvisser** [comment]
I've tried to reproduce this on my own project with AGP 7.2.0, Gradle 7.4.2 and Kotlin 1.6.10, but I'm unable to reproduce in that project unfortunately.

**Comment by michaelcarrano** [comment]
Not ideal but so far seems like if I add the following to `buildSrc/build.gradle` then things are working with the right Jackson version.
```
implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.13.0'
```
or if using version catalog, this is how I reference it: `implementation(libs.jackson)`

Using the above since that is what is defined here: https://github.com/littlerobots/version-catalog-update-plugin/blob/c935a45f4516cbb44470a7a881f31dc7501afc98/catalog/build.gradle#L8

**Comment by hvisser** [comment]
I'd still be very interested to know where that conflicting dependency is coming from. I can imagine that if it's included on `buildSrc` somehow in your specific project it would override all plugins, but I'm not sure if the same happens if you include some other plugin in other ways. So if you can repro or provide a build scan for more insights that would be great.

**Comment by Nek-12** [comment]
I'm facing the same issue here. Unable to update dependencies because of that.
Kotlin 1.6.21 Gradle 7.4.2 AGP 7.2.0

**Comment by hvisser** [comment]
Same question: can you provide a small project and/or a build scan that reproduces this @Nek-12?

**Comment by Nek-12** [comment]
I'd like to, but I'm not sure about how to create a minimal repro for you. I don't even know which of the hundreds of dependencies in a project is using Jackson. I will look into it, but I can't promise a result.

**Comment by hvisser** [comment]
Does the workaround that @michaelcarrano provided work for you? Running a gradle build scan will probably show where that other dependency is coming from too (run the build from the command line with `--scan`). I'd like to understand the prevalence and cause of this issue before I attempt a fix preferably.

**Comment by ivanalvarado** [comment]
I'm still trying to repro on small project, but adding 
```groovy
implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.13.0")
```
to `buildSrc/build.gradle.kts` works.

In the meantime, here's some of the stacktrace:
```
Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.databind.cfg.MutableCoercionConfig com.fasterxml.jackson.dataformat.toml.TomlMapper.coercionConfigDefaults()'
        at com.fasterxml.jackson.dataformat.toml.TomlMapper.<init>(TomlMapper.java:75)
        at com.fasterxml.jackson.dataformat.toml.TomlMapper.<init>(TomlMapper.java:68)
        at nl.littlerobots.vcu.VersionCatalogParser.parse(VersionCatalogParser.kt:42)
        at nl.littlerobots.vcu.plugin.VersionCatalogUpdateTask.updateCatalog(VersionCatalogUpdateTask.kt:108)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)

```

**Comment by hvisser** [comment]
I ran into a similar issue myself today where `okio` is added to the build classpath by this plugin, breaking plugins that need a newer version. A workaround is to set the correct dependency on the `buildScript` block, but the real fix would probably be bundling / shading the dependencies using https://github.com/GradleUp/gr8

**Comment by hvisser** [comment]
I think I have a fix now. I would really appreciate it if someone could verify that this works for them, by testing if `0.5.4-SNAPSHOT` resolves this issue. You'll have to add the snapshots repository to your settings file to use that version, something like:

```
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
       // add this
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
}
```

This can be potentially be a tricky update to just release on a whim so the more eyes on it the better 🙏

**Comment by Nek-12** [comment]
I've verified that version 0.5.4-SNAPSHOT does not have this issue anymore. My project is not using jackson.

**Comment by hvisser** [comment]
Thanks for testing! I also think this fixes it so will merge and release soonish ;)
