### ISSUE TITLE
keepUnused flag not respected for entries under [versions]

### ISSUE THREAD

**Issue by kyhule** [littlerobots/version-catalog-update-plugin#4]
This use-case might be a misuse of the version catalog but our project stores versions that while aren't referenced within the TOML file, they are referenced by the project (e.g. `compileSdk` version used in android gradle plugin).
```kotlin
android {
    compileSdk = libs.versions.compileSdk.get().toInt()
}
```

 I assumed setting `keepUnused = true` would solve this but "unused" version declarations were still removed when running `versionCatalogUpdate`. I did verify that `keepUnused = true` was indeed working for unused library declarations.

**Comment by hvisser** [comment]
Ah I see...that's definitely creative, but maybe valid? (I'm not sure). Keep unused currently only applies to libraries, and will still prune versions as you noticed, so either it should retain versions if `keepUnused` is true too or maybe `keepUnused` should allow you to specify what to keep.

It might be reasonable to just not prune versions for `keepUnused` for now and see if different "keep" levels make sense later.

**Comment by hvisser** [comment]
`0.2.0-SNAPSHOT` has this change applied if you want to give it a try before the next release (probably somewhere this week).

**Comment by kyhule** [comment]
I can't say I'm the first to do it and will definitely not be the last. That being said, immediately after creating this issue I realized the value in the plugin removing obsolete version declarations that may not have been cleaned up even if you don't want to remove old dependencies. Still, keeping it some sounds good for now. 

Thanks for publishing this plugin! I randomly stumbled upon it today looking for a example of version catalog plugin. I've tried so many plugins that haven't worked out for me for one reason or another but this looks great! 👍

**Comment by hvisser** [comment]
Thanks, that's great to hear. And thanks again for the feedback as I'm also figuring out what makes the most sense for general use vs what I think makes sense :)

**Comment by Egorand** [comment]
Just stumbled upon this issue in `0.4.0`, I've got the exact same use case as @kyhule. While there is the `keepUnusedVersions` property I can use, I think it's useful to have the plugin remove versions that are legitimately not used, hence ideally I wouldn't want to set this property to true. The plugin removing versions that are in fact used feels like a bug. Happy to open another ticket and share a repro project if that helps!

P.S. Thanks for a great plugin!

**Comment by hvisser** [comment]
Hmm there are tests for that I think so if you have a small reproducible case where used versions (used in _dependencies_!) are removed then I'd be interested in that. 

Versions that are used like in the example, not used in any dependency, will always need a keep configuration. You don't need to keep _all_ versions in recent versions of the plugin, you can specify exactly which one to keep using config or `# @keep` as a comment above the version you want to keep, see the readme for details on that.

**Comment by Egorand** [comment]
Well, these versions do not fit the definition of "used in dependencies" - they're simply referenced in `build.gradle` files. `@keep`-ing them individually probably makes sense to me, since version catalog is not really designed for storing non-dependency versions, so `@keep` is a small price to pay for convenience!
