### ISSUE TITLE
Allow control of bundle formatting

### ISSUE THREAD

**Issue by dalewking** [littlerobots/version-catalog-update-plugin#44]
If you have a log of items in a bundle it is much better to put them on multiple lines as in:

```
myBundle = [
    "dependency1",
    "dependency2",
    "dependency3",
]
```

I also prefer the trailing comma to reduce diffs when adding a line

However this plugin always forces it into one line which makes for very long, unreadable lines. In my project I have a bundle that it forces into a 275 character line.

You should allow control of whether it is broken up, with perhaps a break it up if if is over x line length and also whether to use trailing comma when you do.

**Comment by hvisser** [comment]
Agreed that one single line is not ideal :) Would limiting the line length and adding a trailing comma be acceptable for your use case? I rather not have tons of options to configure this vs having a sensible, opinionated default.

**Comment by dalewking** [comment]
If, you put the values in the array on. separate lines if it does not fit on one line, then yes. My use case is that I always want all entries in the bundle to be on separate lines, so the sensible, opinionated default in my mind is never try to squeeze it into one line.
