### ISSUE TITLE
Support for multiple TOML files (needs more feedback)

### ISSUE THREAD

**Issue by hvisser** [littlerobots/version-catalog-update-plugin#52]
This comes up now and then (#46, #20), though I'm not 100% sure on the use case so please chime in!

One use case I can think of is for organisation purposes, where you'd like to split up the dependencies over multiple catalog files.

With manual configuration of the update task, this is currently already possible, however it would be nice if the plugin could set that up for you. The proposed solution would look something like this:

* Specify the TOML files considered for updating in the `versionCatalogUpdate` extension
* Configure an update task for each TOML file with the `versionCatalogUpdate` task running all of them; this allows to update a single catalog file (need to figure out how to get some kind of identifier for each file)
* Same for formatting tasks (new as of 0.5.0)

Potential issues:
* The `--add` and `--create` command line options would be weird to run on all catalogs, so if possible those should be only available on the non-aggregating task

**Comment by ivanalvarado** [comment]
We have a use case for this feature request. My team has broken up Version Catalogs into multiple toml files for organizational purposes. 

> With manual configuration of the update task, this is currently already possible

Do you have an example of this?

**Comment by hvisser** [comment]
I don't have an example handy, I was going on the report from a user that said they configured additional tasks, but with recent changes it's probably a bit harder (though not impossible). You'd basically have to do something like what the plugin is doing for the main task: https://github.com/littlerobots/version-catalog-update-plugin/blob/main/plugin/src/main/kotlin/nl/littlerobots/vcu/plugin/VersionCatalogUpdatePlugin.kt#L48

**Comment by hvisser** [comment]
Decided to not change the existing tasks, but to configure additional tasks by specifying additional toml files in the configuration:

```
versionCatalogUpdate {
      versionCatalogs {
          libs2 {
              catalogFile = file("libs2.versions.toml")
          }
      }
  }
```

This config will then add tasks for `versionCatalogUpdateLibs2`, `versionCatalogFormatLibs2` etc.
