### ISSUE TITLE
Setting `sortByKey` to `false` still reorders section

### ISSUE THREAD

**Issue by sschuberth** [littlerobots/version-catalog-update-plugin#58]
Although strictly speaking "sections" are not "keys", I'd expect that setting `sortByKey` to `false` leaves the formatting of my whole `gradle/libs.versions.toml` alone, including the order of the `[versions]`, `[plugins]`, `[libraries]` and `[bundles]` sections, and any custom blank lines added for formatting in between.

What happens instead is that blank lines seem to be stripped, and sections being reordered.

**Comment by hvisser** [comment]
Yes, the tables are always rewritten in this order and white space like blank lines are not recorded during parsing. Would this prevent you from using the plugin or could you just accept the format like for example a code formatter like ktlint does? The benefit in my opinion that this prevents bike shedding conversations around the catalog toml file format, like other code formatting tools do (so in I'd consider this a feature myself 😁)

**Comment by sschuberth** [comment]
> Would this prevent you from using the plugin

No, it wouldn't, I just [took it into use](https://github.com/oss-review-toolkit/ort/pull/5491) 😁

> this prevents bike shedding conversations around the catalog toml file format

Well, I'd argue an even better way to avoid bike shedding here is not not touch the formatting at all 😉

Anyway, if it's just to inconvenient to avoid sorting the section, feel free to close. Personally, I'm anyway committing each version update separately to be able to link the library's changelog in the commit message, so I can as well omit diff hunks that just touch the formatting.
