### ISSUE TITLE
Upgrade to kotest not reflected

### ISSUE THREAD

**Issue by sschuberth** [littlerobots/version-catalog-update-plugin#59]
Running `./gradlew versionCatalogUpdate` on *main* of https://github.com/oss-review-toolkit/ort shows

```
The following dependencies have later milestone versions:
 - io.kotest:kotest-assertions-core [5.3.1 -> 5.3.2]
     https://github.com/kotest/kotest
 - io.kotest:kotest-assertions-json [5.3.1 -> 5.3.2]
     https://github.com/kotest/kotest
 - io.kotest:kotest-extensions-junitxml [5.3.1 -> 5.3.2]
     https://github.com/kotest/kotest
 - io.kotest:kotest-framework-api [5.3.1 -> 5.3.2]
     https://github.com/kotest/kotest
 - io.kotest:kotest-framework-engine [5.3.1 -> 5.3.2]
     https://github.com/kotest/kotest
```

but still the upgrade of kotest is not reflected in the TOML changes. Any idea why? Is there a problem with test-only dependencies?

**Comment by hvisser** [comment]
If the versions plugin is detecting them, that shouldn't be a problem. I'll take a look to see if I can reproduce and find the cause.

**Comment by hvisser** [comment]
If I run a clean build, it fails because there's no `report.json` generated. The cause of this is that you are setting the outputFormatter to `null` [here](https://github.com/oss-review-toolkit/ort/blob/main/build.gradle.kts#L98) (overriding what the plugin is setting). The task was probably picking up an existing json and therefore not updating nor breaking. To fix, set the outputFormatter to "json" or don't null it at all.

**Comment by sschuberth** [comment]
> To fix, set the outputFormatter to "json" or don't null it at all.

Oh, that's subtle! I wasn't aware that this plugin is actually just parsing the version plugin's reports. It there maybe a safer way by just using the version tasks output programmatically somehow?

**Comment by hvisser** [comment]
The versions plugin has a way (meant for custom reports), but using the output file is more common in Gradle and it allows for scenarios where that input file is generated in other ways (decoupling the the versions plugin from this plugin).

**Comment by sschuberth** [comment]
Hmm, isn't this code supposed to override the configuration of the `dependencyUpdates` task to always include the JSON report?

https://github.com/littlerobots/version-catalog-update-plugin/blob/40167aff480889248f590200b1def41774f299e6/plugin/src/main/kotlin/nl/littlerobots/vcu/plugin/VersionCatalogUpdatePlugin.kt#L72

**Comment by hvisser** [comment]
It is, but apparently the config in your build file can override this again.

**Comment by sschuberth** [comment]
So, would it maybe help to move this so some `afterEvaluate` block so the (re-)configuration of the `dependencyUpdates` task done by this plugin happens last?

**Comment by hvisser** [comment]
Yeah that might be an option if the config isn't locked at that point (and if that plays ball with configuration caching), though AFAIK the general recommendation is to avoid `afterEvaluate`, so I'm not 100% sure here. That would only be needed for the output formatter, the rest we'd still want to be allowed to be overridden in the build script.

**Comment by sschuberth** [comment]
I'm closing this as the original issue was solved.
