### ISSUE TITLE
`versionCatalogUpdate` task failing on `Collection contains no element matching the predicate`

### ISSUE THREAD

**Issue by PawelLipski** [littlerobots/version-catalog-update-plugin#61]
It's unclear what collection is even being referenced... also, the update to libs.versions.toml happens nevertheless!

```
> Task :versionCatalogUpdate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':versionCatalogUpdate'.
> Collection contains no element matching the predicate.
```

Not much can be inferred from `--info` logs either.

Full repro: the current state of https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1009, i.e. https://github.com/VirtusLab/git-machete-intellij-plugin/tree/bffe9f95ef0b32e674c209ea58b07e0243ebdc80

**Comment by hvisser** [comment]
Thanks for the repro, that really helps a lot! Running `./gradlew versionCatalogUpdate --stacktrace` reveals where that exception is thrown:

```
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at nl.littlerobots.vcu.plugin.VersionCatalogUpdateTask.checkForUpdatedPinnedPlugins(VersionCatalogUpdateTask.kt:589)
        at nl.littlerobots.vcu.plugin.VersionCatalogUpdateTask.updateCatalog(VersionCatalogUpdateTask.kt:154)
```

That's indeed after the catalog is updated for outputting information on pinned plugins. I'll need to dig in a bit deeper to see what condition is causing this still.

**Comment by hvisser** [comment]
This happens when plugins (or libraries) that are pinned are no longer used, but still kept through configuration. The dependency plugin will not report them, but the warning check still assumes there should be an entry in the catalog, failing to find them in the updates.

**Comment by PawelLipski** [comment]
Whoops yes, that's (kind of) my case... I can't unfortunately get rid of that, that's already a workaround for https://github.com/ben-manes/gradle-versions-plugin/issues/284: see https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1013 for more details!

**Comment by PawelLipski** [comment]
Would it be possible for you to handle this pinned&unused case without an error? 🙏🏻

**Comment by hvisser** [comment]
Yeah, it should just ignore that dependency in that case and not crash :) It only affects that warning.

**Comment by PawelLipski** [comment]
Btw, as we're speaking now... do you know of any better workaround for `versionCatalogUpdate` (or rather, the underlying `dependenciesUpdate`) NOT working for dependencies of `buildSrc`? this seems to be a common problem :/

**Comment by hvisser** [comment]
> Btw, as we're talking now... do you know of any better workaround for `versionCatalogUpdate` (or rather, the underlying `dependenciesUpdate`) NOT working for dependencies of `buildSrc`? this seems to be a common problem :/

I'm not using `buildSrc` in my projects so I don't have an answer to that, but I can imagine it's a tricky problem if there is even an API to get to those dependencies...

**Comment by PawelLipski** [comment]
Gr8, thanks for super-quick fix 🐎 looking forward to a release now

**Comment by hvisser** [comment]
Should be on Maven Central shortly.

**Comment by PawelLipski** [comment]
Out of curiosity... is there a reason why you host this plugin on Maven Central rather than on Gradle Plugin Portal?

**Comment by hvisser** [comment]
No particular reason other than I had publishing setup for Maven Central already. Could consider to publish to the Gradle plugin portal before I call it 1.0.0 maybe.

**Comment by PawelLipski** [comment]
Hmmm it seems that this fix is NOT included in v0.5.2:

https://github.com/littlerobots/version-catalog-update-plugin/compare/v0.5.1...v0.5.2 => just some bookkeeping
https://github.com/littlerobots/version-catalog-update-plugin/compare/v0.5.2...main => actual fix is still unreleased

**Comment by hvisser** [comment]
Hm not sure what went wrong there, thanks for the ping

**Comment by PawelLipski** [comment]
> No particular reason other than I had publishing setup for Maven Central already. Could consider to publish to the Gradle plugin portal before I call it 1.0.0 maybe.

Yeah, would be a good idea... esp. that when applying this plugin to `buildSrc`, a sligthly different DSL block seems to needed than what's in README, dunno why tho. See [VirtusLab/git-machete-intellij-plugin#1018](https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1018/files) -> `buildSrc/settings.gradle.kts`
