### ISSUE TITLE
Publish this plugin with a short artifact name?

### ISSUE THREAD

**Issue by Goooler** [littlerobots/version-catalog-update-plugin#67]
Cause I see the artifact name of this is `nl.littlerobots.version-catalog-update:nl.littlerobots.version-catalog-update.gradle.plugin`, it's too long, should we rename it? 

https://search.maven.org/artifact/nl.littlerobots.version-catalog-update/nl.littlerobots.version-catalog-update.gradle.plugin/0.3.0/pom

**Comment by hvisser** [comment]
That's not the artifact you are looking for, that's the Gradle plugin marker. You need `nl.littlerobots.vcu:plugin:<version>` if you want to apply this plugin in the build script block.
