### ISSUE TITLE
Non-standard TOML file location

### ISSUE THREAD

**Issue by michaeloa** [littlerobots/version-catalog-update-plugin#92]
It would be really nice to be able to specify the location of the libs.versions.toml, if it is not in the standard location (gradle/...). Alternatively, to pick up the location from settings,xml.

Tried to use the multiple catalog files for this purpose, but that does not work in gradle.kts (also isn't really the right solution to this issue, as the problem would persist that the "base" libs is missing).

**Comment by hvisser** [comment]
Can you provide a small repro sample? I'm not fully understanding why working around specifying additional toml files would not work? I think you could configure the task directly (the `catalogFile` property) with the non-standard location too, but I'd have to try.

**Comment by michaeloa** [comment]
Wasn't able to get it working using Kotlin DSL, but maybe I'm doing it wrong?

I'll see if I can extract a simple example.

**Comment by hvisser** [comment]
I've documented the kts syntax in the README now and the next version will have an option to change the default toml file location if needed.

**Comment by michaeloa** [comment]
Awesome. Thanks, and apologies for not getting back earlier - it slipped my mind in the rush to the holidays.
