### ISSUE TITLE
Plugin ignores versions declared with "strictly"

### ISSUE THREAD

**Issue by aintogarov** [littlerobots/version-catalog-update-plugin#95]
VersionCatalogParser doesn't handle strict versions. For example
```
kotlin = { strictly = "1.7.21" }
``` 

However _com.github.ben-manes.versions_ takes such versions into account and writes them to output.

**Comment by hvisser** [comment]
Can you elaborate and provide a sample project? 

For versions like this I think there should be a message logged, but no upgrades will be performed, since you've specified that you want to use this exact version.

So if you don't see that message, this might be a bug.

**Comment by hvisser** [comment]
OK I checked and the warning that is in place for libraries is not implemented for plugins (because it's slightly more complicated 😅 ) so I assume that is what this issue is about.
